//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitoys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_Country
    {
        public UT_Country()
        {
            this.UT_Package = new HashSet<UT_Package>();
        }
    
        public int ID { get; set; }
        public string CountryName { get; set; }
        public string Pic { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual ICollection<UT_Package> UT_Package { get; set; }
    }
}
