//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitoys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_PayRecord
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string PayBank { get; set; }
        public string Ip { get; set; }
        public int Status { get; set; }
    
        public virtual UT_Users UT_Users { get; set; }
    }
}
