//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitoys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_Package
    {
        public int ID { get; set; }
        public string PackageName { get; set; }
        public decimal Price { get; set; }
        public int Flow { get; set; }
        public string Desction { get; set; }
        public string Pic { get; set; }
        public Nullable<double> Discount { get; set; }
        public int ExpireDays { get; set; }
        public Nullable<int> CountryId { get; set; }
        public int Lock4 { get; set; }
    
        public virtual UT_Country UT_Country { get; set; }
    }
}
