//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitoys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SMS
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string FromNum { get; set; }
        public string ToNum { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string Content { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> IsRead { get; set; }
    
        public virtual UT_Users UT_Users { get; set; }
    }
}
