//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitoys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT_SpeakRecord
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
        public string FromCall { get; set; }
        public string ToCall { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UT_Users UT_Users { get; set; }
    }
}
